### ISSUE TITLE
Error on running bloggy auth

### ISSUE THREAD

**Issue by aerunti** [emmett-framework/emmett#457]
When I try to run bloggy example in version 2.5.1, and go to auth/login, I got the following error:

![image](https://github.com/emmett-framework/emmett/assets/106102441/2c3e8153-ccdb-43fd-b340-c59830748615)

I tried to run bloggy because when I followed the docs and tried to run auth/login, I got the same error. 

So I tried other versions, it runs with 2.4.14. 

So the new versions (2.5.0 and 2.5.1) introduced a bug on 

    auth_routes = auth.module(__name__)

or need a (undocumented) configuration. 

any tips are welcome to run on new versions.

**Comment by gi0baro** [comment]
@aerunti there was a `contextvars.Context` issue with granian 0.4.0, which has been fixed in 0.4.1 (ref: https://github.com/emmett-framework/granian/releases/tag/v0.4.1).

Upgrading dependencies should fix it.

**Comment by aerunti** [comment]
> @aerunti there was a `contextvars.Context` issue with granian 0.4.0, which has been fixed in 0.4.1 (ref: https://github.com/emmett-framework/granian/releases/tag/v0.4.1).
> 
> Upgrading dependencies should fix it.

unfortunately, it didn't solve it. Granian 0.4.1 is installed and problem persists. Looks the form isn't generated or some string for translation need be configurated. 

There is a command to generate a (updated) en.json with all strings to be moved to other language name, like pt.json or es.json and translated?

**Comment by gi0baro** [comment]
This is now fixed with granian 0.4.2
